name: "Continuous integration"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Sync
        run: uv sync --all-extras
      - name: Pre-Commit Hooks
        run: uv run pre-commit run --all-files
      - name: Test
        run: uv run pytest
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: false
          verbose: true
